import js from "@eslint/js";

export default [
  js.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "commonjs",
      globals: {
        console: "readonly",
        process: "readonly",
        Buffer: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        __dirname: "readonly",
        require: "readonly",
        module: "readonly",
        exports: "readonly",
        document: "readonly",
        window: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        fetch: "readonly",
        Request: "readonly",
        Response: "readonly",
        Headers: "readonly",
        AbortController: "readonly",
        TextDecoder: "readonly",
        TextEncoder: "readonly",
        WebSocket: "readonly",
        FormData: "readonly",
        Blob: "readonly",
        File: "readonly",
        FileReader: "readonly",
        Image: "readonly",
        HTMLElement: "readonly",
        HTMLInputElement: "readonly",
        HTMLSelectElement: "readonly",
        HTMLButtonElement: "readonly",
        HTMLDivElement: "readonly",
        HTMLSpanElement: "readonly",
        Event: "readonly",
        CustomEvent: "readonly",
        CustomEventInit: "readonly",
        KeyboardEvent: "readonly",
        MouseEvent: "readonly",
        FocusEvent: "readonly",
        InputEvent: "readonly",
        PointerEvent: "readonly",
        ClipboardEvent: "readonly",
        DragEvent: "readonly",
        WheelEvent: "readonly",
        UIEvent: "readonly",
        ErrorEvent: "readonly",
        PromiseRejectionEvent: "readonly",
        EventTarget: "readonly",
        Node: "readonly",
        NodeList: "readonly",
        Element: "readonly",
        SVGElement: "readonly",
        SVGSVGElement: "readonly",
        MutationObserver: "readonly",
        IntersectionObserver: "readonly",
        ResizeObserver: "readonly",
        DOMParser: "readonly",
        XMLSerializer: "readonly",
        XMLHttpRequest: "readonly",
        Crypto: "readonly",
        crypto: "readonly",
        btoa: "readonly",
        atob: "readonly",
        structuredClone: "readonly",
        Worker: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        location: "readonly",
        navigator: "readonly",
        history: "readonly",
        screen: "readonly",
        alert: "readonly",
        confirm: "readonly",
        prompt: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        getComputedStyle: "readonly",
        matchMedia: "readonly",
        getSelection: "readonly",
        scrollTo: "readonly",
        scrollBy: "readonly",
        queueMicrotask: "readonly",
        reportError: "readonly",
      },
    },
    rules: {
      "no-var": "off",
      "prefer-const": "off",
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
      semi: ["error", "always"],
      quotes: ["error", "double", { avoidEscape: true }],
      eqeqeq: ["error", "always"],
      "no-throw-literal": "error",
      "no-return-await": "off",
      "require-await": "off",
      "no-constant-condition": ["error", { checkLoops: false }],
      "no-irregular-whitespace": "off",
      "no-empty": ["error", { allowEmptyCatch: true }],
    },
  },
  {
    ignores: ["dist/**", "node_modules/**", "out/**", "src/ui/assets/**"],
  },
];
